/**
 * Default config for Alibaba-B2B-ICBU-F2E develop environment.
 * Auto-generated by Tianma v<%=version%>
 */

var tianma = require('tianma'),
	pipe = tianma.pipe;

tianma({ silent: <%=silent%>, log: <%=log%> })
	.createHost({ port: 80, portssl: 443 })
		.mount('style.aliunicorn.com', [ // unicorn service
			pipe.combo({ source: 'http://style.alibaba.com/' })
		])
		.mount('/', [ // static service
			pipe.static({ root: './htdocs' }),
			pipe.proxy({
				'http://110.75.216.150/$1': /(?:(?:style|img)\.(?:alibaba|aliexpress)\.com|aliimg\.com)\/(.*)/
			}),
			pipe.beautify()
		])
		.start();
