/**
 * Default config for Alibaba-B2B-ICBU-F2E develop environment.
 * Auto-generated by Tianma v<%=version%>
 */

var tianma = require('tianma'),
	pipe = tianma.pipe;

tianma
	.init({ silent: <%=silent%>, log: <%=log%> })
	.createHost({ port: 80, portssl: 443 })
		.mount('style.aliunicorn.com', [ // unicorn service
			pipe.unicorn({ roots: [ './htdocs', 'http://style.alibaba.com/' ] }),
			pipe.beautify()
		])
		.mount('/', [ // static service
			pipe.static({ wwwroot: './htdocs' }),
			pipe.proxy({
				'http://110.75.216.150/$1': /(?:(?:style|img)\.alibaba\.com|aliimg\.com)\/(.*)/
			}),
			pipe.beautify()
		])
		.start();
