#!/bin/bash

if ! command -v node > /dev/null
then
  echo "Please visit http://nodejs.org/ and install NodeJS first."
  exit 1
fi

if ! command -v tianma > /dev/null
then
  echo "Please run \"npm install tianma -g\" to install Tianma first."
  exit 1
fi

echo "Press [Ctrl+C] to stop service.."
echo ""

export NODE_PATH=`tianma libpath`
if [ -z "$1" ]
then
	node config.js
else
	node $1
fi
