#!/bin/bash

if ! command -v node > /dev/null
then
	echo "Please visit http://nodejs.org/ and install NodeJS first."
	exit 1
fi

if ! command -v tianma > /dev/null
then
	echo "Please run \"npm install tianma -g\" to install Tianma first."
	exit 1
fi

if [ -f ".pid" ]
then
	pid=$(tr -d '\r\n' < .pid)
	if ps -f -p $pid | grep "node" > /dev/null
	then
		echo "service is running"
		exit 1
	fi
fi

if [ ! -d ".log" ]
then
	mkdir .log
fi

echo "service started"
logfile=$(printf "%s.log" $(date +%Y-%m-%d))
export NODE_PATH=`tianma libpath`
if [ -z "$1" ]
then
	node config.js &> .log/$logfile &
else
	node $1 &> .log/$logfile &
fi
echo $! > .pid
exit 0